name: Build and Deploy Python App with MySQL

on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'docs/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/*'

jobs:
  build:
    runs-on: [self-hosted, linux, office-laptop]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker-compose -f docker/docker-compose.yml build

      - name: Run Docker containers
        run: |
          docker-compose -f docker/docker-compose.yml up -d
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      # Clean up Docker containers after the job
      - name: Clean up Docker containers
        run: |
          docker-compose -f docker/docker-compose.yml down

