name: Python and MySQL CI/CD Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/*'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=30s

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Run database migrations (if any) or initialize DB with tables
      - name: Run database migrations
        run: |
          python -c "import mysql.connector; conn = mysql.connector.connect(host='localhost', user='root', password='my-secret-pw', database='testdb'); cursor = conn.cursor(); cursor.execute('CREATE TABLE IF NOT EXISTS my_table (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255))'); cursor.execute('INSERT INTO my_table (name) VALUES (\"Test\")'); conn.commit(); conn.close()"

      # Run tests (Optional)
      - name: Run tests
        run: |
          python -m unittest discover

      # Deploy to Production (Optional)
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
